name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        php-version: [5.5, 5.6, 7.0, 7.1]

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2 
        with:
          php_version: ${{ matrix.php-version }}
          configuration: tests/phpunit.xml
